export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_MODULE = 'SET_CURRENT_MODULE';
export const SET_CURRENT_AUTH = 'SET_CURRENT_AUTH';
export const SET_TASK_TOTAL = 'SET_TASK_TOTAL';

